import Image1 from "../assets/images/all-nfts/image1.png";
import Image2 from "../assets/images/all-nfts/image2.png";
import Image3 from "../assets/images/all-nfts/image3.png";
import Image4 from "../assets/images/all-nfts/image4.png";
import Profile1 from "../assets/images/all-nfts/profile1.png";
import Profile2 from "../assets/images/all-nfts/profile2.png";
import Profile3 from "../assets/images/all-nfts/profile3.png";
import Profile4 from "../assets/images/all-nfts/profile4.png";

export const data = [
  {
    id: 0,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Art",
  },
  {
    id: 1,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Art",
  },
  {
    id: 2,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Art",
  },
  {
    id: 3,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Art",
  },
  {
    id: 4,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Art",
  },
  {
    id: 5,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Music",
  },
  {
    id: 6,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Music",
  },
  {
    id: 7,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Music",
  },
  {
    id: 8,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Music",
  },
  {
    id: 9,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Sport",
  },
  {
    id: 10,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Sport",
  },
  {
    id: 11,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Gaming",
  },
  {
    id: 12,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Gaming",
  },
  {
    id: 13,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Gaming",
  },
  {
    id: 14,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Gaming",
  },
  {
    id: 15,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Gaming",
  },
  {
    id: 16,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Gaming",
  },
  {
    id: 17,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Celebrities",
  },
  {
    id: 18,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Celebrities",
  },
  {
    id: 19,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Celebrities",
  },
  {
    id: 20,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Crypto",
  },
  {
    id: 21,
    image: Image2,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Crypto",
  },
  {
    id: 22,
    image: Image3,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Crypto",
  },
  {
    id: 23,
    image: Image4,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Crypto",
  },
];
