import Image1 from "../assets/images/all-nfts/image1.png";
import Image10 from "../assets/images/all-nfts/image10.jpg";
import Image11 from "../assets/images/all-nfts/image11.jpeg";
import Image12 from "../assets/images/all-nfts/image12.jpeg";
import Image13 from "../assets/images/all-nfts/image13.jpeg";
import Image14 from "../assets/images/all-nfts/image14.jpeg";
import Image15 from "../assets/images/all-nfts/image15.jpeg";
import Image16 from "../assets/images/all-nfts/image16.webp";
import Image17 from "../assets/images/all-nfts/image17.jpeg";
import Image2 from "../assets/images/all-nfts/image2.png";
import Image5 from "../assets/images/all-nfts/image5.jpg";
import Image6 from "../assets/images/all-nfts/image6.jpg";
import Image7 from "../assets/images/all-nfts/image7.jpg";
import Image8 from "../assets/images/all-nfts/image8.jpg";
import Image9 from "../assets/images/all-nfts/image9.jpg";
import Profile1 from "../assets/images/all-nfts/profile1.png";
import Profile2 from "../assets/images/all-nfts/profile2.png";
import Profile3 from "../assets/images/all-nfts/profile3.png";
import Profile4 from "../assets/images/all-nfts/profile4.png";

export const data = [
  {
    id: 0,
    image: Image7,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Art",
  },
  {
    id: 1,
    image: Image1,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Art",
  },
  {
    id: 2,
    image: Image5,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Art",
  },
  {
    id: 3,
    image: Image6,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Art",
  },
  {
    id: 4,
    image: Image2,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Art",
  },
  {
    id: 5,
    image: Image8,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Music",
  },
  {
    id: 6,
    image: Image9,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Music",
  },
  {
    id: 7,
    image: Image10,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Music",
  },
  {
    id: 8,
    image: Image11,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Music",
  },
  {
    id: 9,
    image: Image12,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Sport",
  },
  {
    id: 10,
    image: Image13,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Sport",
  },
  {
    id: 11,
    image: Image14,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Gaming",
  },
  {
    id: 12,
    image: Image15,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Gaming",
  },
  {
    id: 13,
    image: Image16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Gaming",
  },
  {
    id: 14,
    image: Image17,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Gaming",
  },
  {
    id: 15,
    image: Image5,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Gaming",
  },
  {
    id: 16,
    image: Image7,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Gaming",
  },
  {
    id: 17,
    image: Image9,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Celebrities",
  },
  {
    id: 18,
    image: Image6,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Celebrities",
  },
  {
    id: 19,
    image: Image8,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Celebrities",
  },
  {
    id: 20,
    image: Image12,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "ArtCrypto",
    category: "Crypto",
  },
  {
    id: 21,
    image: Image10,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "This NFT",
    category: "Crypto",
  },
  {
    id: 22,
    image: Image11,
    radius: 11,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "NameCrypto",
    category: "Crypto",
  },
  {
    id: 23,
    image: Image17,
    radius: 13.16,
    profileImage1: Profile4,
    profileImage2: Profile2,
    profileImage3: Profile1,
    profileImage4: Profile3,
    name: "KingCrypto",
    category: "Crypto",
  },
];
